config/routes.rb
Rails.application.routes.draw do
  root             'static_pages#home'
  get 'help'    => 'static_pages#help'
  get 'about'   => 'static_pages#about'
  get 'contact' => 'static_pages#contact'
  get 'signup'  => 'users#new'
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'
  resources :users
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]
  

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def help
  end
  
  def about
  end
  
  def contact
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/about.html.erb
<% provide(:title, "About") %>
<h1>About</h1>
<p>
  <a href="http://www.developingmusicianship.com/"><em>Developing Musicianship</em></a> is a
  company specialising in the development of musicianship through iPad, iPhone and online
  ear training and theory applications.
  This is the beginnings of an application for the online component.
</p>

app/views/static_pages/contact.html.erb
<% provide(:title, 'Contact') %>
<h1>Contact</h1>
<p>
  Contact Developing Musicianship for information regarding the available 
  music education resources for iPad, iPhone and online applications.
  <a href="http://www.developingmusicianship.com/#contact">contact page</a>.
</p>

app/views/static_pages/help.html.erb
<% provide(:title, "Help") %>
<h1>Help</h1>
<p>
  Get help and information on Developing Musicianship products at
  <a href="http://www.developingmusicianship.com/#help">Developing Musicianship help section</a>.
  To discuss any matters directly, contact
  <a href="mailto:markelshout@yahoo.com"><em>Mark Elshout</em>
</a>.
</p>

app/views/static_pages/home.html.erb
<div class="center jumbotron">
<h1>MusicEd Online</h1>
<h2>
  This is the home page for the
  <a href="http://www.developingmusicianship.com/">MusicEd Online - Developing Musicianship</a>
</h2>

<%= link_to "Sign up now!", signup_path, class: "btn btn-lg btn-primary" %>
</div>

<%= link_to image_tag("rails.png", alt: "Rails logo"),
            'http://rubyonrails.org/' %>